theme: jekyll-theme-minimal

title: AST image processing Quick Start
description: This page contains an overview of the library with examples.

logo: images/400px_ASTimp_icon.png
show_downloads: false
# google_analytics: Your Google Analytics tracking ID